<?php

return [
    'kantor' => [
        [
            'id' => 1,
            'nama' => 'Kantor Pusat PT BPR NTB PERSERODA',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.565730445185917,
            'longitude' => 116.07849753374737,
            'tipe' => 'Pusat',
        ],
        [
            'id' => 2,
            'nama' => 'PT BPR NTB PERSERODA KPOKP',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.566038110783627,
            'longitude' => 116.07849552208928,
            'tipe' => 'POKP',
        ],
        [
            'id' => 3,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Gerung',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.6847657,
            'longitude' => 116.1242950,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 4,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Narmada',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5959348,
            'longitude' => 116.2008912,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 5,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuapi',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.6341938,
            'longitude' => 116.0946244,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 6,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kuripan',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.6612032,
            'longitude' => 116.1588660,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 7,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Gunung Sari',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.542477,
            'longitude' => 116.105307,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 8,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kayangan',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.256854,
            'longitude' => 116.257468,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 9,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bayan',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.229135300382945,
            'longitude' => 116.42039019876431,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 10,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.703983,
            'longitude' => 116.266885,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 11,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya Timur',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.762328,
            'longitude' => 116.351488,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 12,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Janapria',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.697101,
            'longitude' => 116.403701,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 13,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Batukliang',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.624447,
            'longitude' => 116.309078,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 14,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Pujut',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.80812,
            'longitude' => 116.295388,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 15,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Jonggat',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.653124,
            'longitude' => 116.200380,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 16,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kopang',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.631720,
            'longitude' => 116.347142,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 17,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya Barat',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.742034851410793,
            'longitude' => 116.24200641657487,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 18,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Pringgarata',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.6189455,
            'longitude' => 116.2525291,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 19,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Selong',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.65010697928796,
            'longitude' => 116.53587279104221,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 20,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Montong Betok',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5977326,
            'longitude' => 116.401330421,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 21,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kotaraja',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.592443259199676,
            'longitude' => 116.42260464130234,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 22,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Paokmotong',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.6273252,
            'longitude' => 116.4577650,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 23,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Dasan Lekong',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.59830714076589,
            'longitude' => 116.52336947680963,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 24,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Aikmel',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.568140,
            'longitude' => 116.532917,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 25,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuhan Lombok',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.504950713963344,
            'longitude' => 116.66126824657722,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 26,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sambelia',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.3889390,
            'longitude' => 116.7138969,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 27,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Taliwang',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.744090,
            'longitude' => 116.847420,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 28,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Seteluk',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.626904,
            'longitude' => 116.864308,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 29,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sumbawa',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.488132101223862,
            'longitude' => 117.41755017332956,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 30,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Empang',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.76889,
            'longitude' => 118.00286,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 31,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Plampang',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.797363923089362,
            'longitude' => 117.77908755406888,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 32,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Lopok',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.611778,
            'longitude' => 117.568306,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 33,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Moyo',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.520937,
            'longitude' => 117.492830,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 34,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Lenangguar',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.733434750717333,
            'longitude' => 117.36353479304607,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 35,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuhan Sumbawa',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.470911,
            'longitude' => 117.399008,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 36,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Utan',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.4128625,
            'longitude' => 117.1345781,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 37,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Alas',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5152082,
            'longitude' => 116.9938045,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 38,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Dompu',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.539311,
            'longitude' => 118.462102,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 39,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Montabaru',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.547335,
            'longitude' => 118.431802,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 40,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Soriutu',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5190343,
            'longitude' => 118.3221665,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 41,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Rasabou',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.739663,
            'longitude' => 118.437720,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 42,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bima',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.453797,
            'longitude' => 118.724051,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 43,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Woha',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.587800630949802,
            'longitude' => 118.69631872204275,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 44,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bolo',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.505445972949396,
            'longitude' => 118.61859376306816,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 45,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sape',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5745870,
            'longitude' => 118.9988758,
            'tipe' => 'Cabang',
        ],
        [
            'id' => 46,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Bertais',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.5969642,
            'longitude' => 116.1550687,
            'tipe' => 'Kas',
        ],
        [
            'id' => 47,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Seketeng',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.507628,
            'longitude' => 117.428642,
            'tipe' => 'Kas',
        ],
        [
            'id' => 48,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Buer',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.462630,
            'longitude' => 117.040857,
            'tipe' => 'Kas',
        ],
        [
            'id' => 49,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Labuhan Jambu',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.696667,
            'longitude' => 118.019681,
            'tipe' => 'Kas',
        ],
        [
            'id' => 50,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Belo',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.553612,
            'longitude' => 118.695286,
            'tipe' => 'Kas',
        ],
        [
            'id' => 51,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Bajo',
            'alamat' => 'Nusa Tenggara Barat',
            'latitude' => -8.455244585728883,
            'longitude' => 118.68376290294685,
            'tipe' => 'Kas',
        ],
    ],
];