<?php

return [
    'mitra' => [
        [
            'id'           => 1,
            'slug'         => 'pawon-pengsong',
            'nama_usaha'   => 'Pawon Pengsong',
            'nama_pemilik' => 'Ibu Nur Aida',
            'bidang_usaha' => 'Makanan & Minuman',
            'lokasi'       => 'Lombok Barat, NTB',
            'telepon'      => '082359191086',
            'deskripsi'    => 'Produsen skala besar produk olahan lokal dengan standar kualitas internasional. Menghadirkan kehangatan Serbat Jahe, Kopi Rempah khas Lombok, serta camilan sehat Biskuit Kelor dan Rumput Laut.',
            'foto'         => 'images/umkm/pawon-1.png',
            'galeri'       => [
                'images/umkm/pawon-2.png',
                'images/umkm/pawon-3.png',
                'images/umkm/pawon-4.png',
                'images/umkm/pawon-5.png',
            ],
            'unggulan'     => 'Serbat, Biskuit Kelor, dan Kopi Jahe',
            'skala'        => 'Internasional',
        ],
        [
            'id'           => 2,
            'slug'         => 'waroh-maju-bersama',
            'nama_usaha'   => 'Waroh Maju Bersama',
            'nama_pemilik' => 'Mainah',
            'bidang_usaha' => 'Makanan & Minuman',
            'lokasi'       => 'Narmada, Lombok Barat',
            'telepon'      => '081805720941',
            'link_instagram' => 'https://instagram.com/Warohmb005',
            'deskripsi'    => 'Merupakan salah satu produsen oleh-oleh khas lombok yang menyediakan berbagai macam makanan olahan yang terbuat dari rumput laut, singkong, pisang, ubi jalar dan talas. semua diolah secara profesional dengan bumbu rempah-rempah tradisional. sehingga menciptakan rasa yang berbeda dengan makanan olahan lainnya',
            'foto'         => 'images/umkm/waroh-1.png',
            'galeri'       => [
                'images/umkm/waroh-2.png',
                'images/umkm/waroh-3.png',
                'images/umkm/waroh-4.png',
                'images/umkm/waroh-5.png',
                'images/umkm/waroh-6.png',
            ],
            'produk_list'  => [
                'Keripik Pisang',
                'Keripik Talas',
                'Keripik Singkong',
                'Keripik Ubi Ungu',
                'Keripik Ubi Madu',
                'Keripik Rumput Laut',
                'Rengginang Singkong',
                'Manisan Tomat',
                'Manisan Rumput Laut',
                'Dodol Nangka',
                'Dodol Pisang',
                'Sale Pisang',
                'Kerupuk Rumput Laut',
                'Kopi',
                'Keripik Pare'
            ],
            'unggulan'     => 'Ceker Rumput Laut, Keripik Pisang, dan Keripik Pare',
            'skala'        => 'Lokal',
            'alamat'       => 'Jln. Suranadi II dusun Penangkep desa sesaot kec. Narmada, Lombok Barat',
        ],
    ],
];
